### ISSUE TITLE
Images not found

### ISSUE THREAD

**Issue by damiencaselli** [pierre-rouanet/poppy-docs#6]
Some images could not be found:

* /img/ergo-jr/3D/multitool.gif
* /img/heol.jpg
* /img/poppyrate.jpg
* /img/network.png
* /img/poppy_home.png
* /img/linux.jpg
* /img/poppy_monitor.png
* /img/logo/gpl-v3.png
* /img/logo/open-source.png
* /img/logo/python.png
* /img/logo/jupyter.png
* /img/notebook-example.png
* /img/humanoid/vrep.png
* /img/torso/explauto-vrep.png
* /img/torso/explauto-res.png
* /img/ergo-jr/electronic/bom.jpg
* /img/ergo-jr/electronic/step-1.jpg
* /img/ergo-jr/electronic/step-2.jpg
* /img/ergo-jr/assembly/xl_320.jpg
* /img/ergo-jr/motorconfig.jpg
* /img/ergo-jr/assembly/ollo_rivet.png
* /img/ergo-jr/assembly/ollo-tool.jpg
* /img/ergo-jr/assembly/xl320_gap.jpg
* /img/ergo-jr/assembly/align-horn.png
* /img/ergo-jr/assembly/step-1-1.jpg
* /img/ergo-jr/assembly/step-1-2.jpg
* /img/ergo-jr/assembly/step-2.jpg
* /img/ergo-jr/assembly/step-3-1.jpg
* /img/ergo-jr/assembly/step-3-2.jpg
* /img/ergo-jr/assembly/step-4-1.jpg
* /img/ergo-jr/assembly/step-4-2.jpg
* /img/ergo-jr/assembly/step-5.jpg
* /img/ergo-jr/assembly/step-6.jpg
* /img/ergo-jr/assembly/step-7.jpg
* /img/ergo-jr/assembly/step-8.jpg
* /img/ergo-jr/assembly/step-9.jpg
* /img/ergo-jr/assembly/ergo-tool-2.jpg
* /img/snap/snap_save.png
* /img/snap/snap_cloud_1.png
* /img/snap/dialog-cloud-signup.png
* /img/snap/snap_login1.png
* /img/snap/snap_login2.png
* /img/snap/logout-menu.png
* /img/snap/snap_open.png
* /img/snap/snap_cloud_3.png
* /img/snap/snap_cloud_5.png
* /img/snap/snap_cloud_4.png
* /img/snap/snap_share_full_screen.png
* /img/snap/snap_xml_save_as.png
* /img/snap/snap_import.png
* /img/snap/find_blocks.png
* /img/snap/find_blocks2.png
* /img/snap/homepage.png
* /img/snap/test_connection.png
* /img/snap/test_connection3.png
* /img/python/banner.png
* /img/python/powered.png
* /img/python/anaconda.png
* /img/python/architecture.png
* /img/python/what-to-install.png
* /img/activity/snap4arduino/montage.jpg
* /img/activity/snap4arduino/connect.png
* /img/activity/snap4arduino/instructions.png
* /img/activity/snap4arduino/map.png
* /img/activity/snap4arduino/instructions_avec_map.png
* /img/python/anaconda_install_path.png
* /img/python/luc_vincent-012.png
* /img/python/luc_vincent-031.png
* /img/vrep/vrep2.png
* /img/vrep/luc_vincent-056.png
* /img/vrep/luc_vincent-059.png
* /img/vrep/luc_vincent-060.png
* /img/vrep/vrep3_1.png
* /img/vrep/vrep3_2.png
* /img/vrep/vrep4.png
* /img/vrep/luc_vincent-070.jpg

**Comment by pierre-rouanet** [comment]
Not sure to understand. They seem to all be on the repo...

**Comment by pierre-rouanet** [comment]
Fixed by f881064fb1d485d2edad110b438558fb868d1325.
